#!/usr/bin/env bash
# Configures a new Ubuntu server with a custom HTTP header response
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "server {
	listen 80 default_server;
	add_header X-Served-By $(hostname);

	root /var/www/html;
	index index.html;

	error_page 404 /404.html;
	location = /404.html{
		internal;
	}

	location /redirect_me {
		return 301 https://www.infotechaccountant.com;
	}

}" > default_file
mv -f default_file /etc/nginx/sites-enabled/default
service nginx restart
