#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy

sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 167388-web-01 3.84.168.177:80 check\n\tserver 167388-web-02 100.26.159.210:80 check\n' /etc/haproxy/haproxy.cfg
service haproxy restart
