#!/usr/bin/env bash
sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-enabled/default
sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-available/default
chown -R nginx:nginx /var/log/nginx /var/lib/nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
pkill -9 apache2
service nginx restart
